

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: minio/minio:RELEASE.2025-07-23T15-54-02Z
  command: server --console-address ":9901" http://minio{1...2}/data{1...2}
  expose:
    - "9900"
    - "9901"
  environment:
    MINIO_ROOT_USER: admin
    MINIO_ROOT_PASSWORD: changeme
  healthcheck:
    test: ["CMD", "mc", "ready", "local"]
    interval: 5s
    timeout: 5s
    retries: 5

# using nginx reverse proxy, load balancing, you can access
# it through port 9900.
services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./.data/data1-1:/data1
      - ./.data/data1-2:/data2
    restart: always

  minio2:
    <<: *minio-common
    hostname: minio2
    volumes:
      - ./.data/data2-1:/data1
      - ./.data/data2-2:/data2
    restart: always

  minio-fe:
    image: nginx:1.29-alpine
    hostname: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "127.0.0.1:9900:9900"
      - "127.0.0.1:9901:9901"
    depends_on:
      - minio1
      - minio2
    restart: always
